apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-webapp.fullname" . }}-config
  labels:
    {{- include "nginx-webapp.labels" . | nindent 4 }}
data:
  nginx.conf: |
    {{- .Values.nginx.config | nindent 4 }}
  index.html: |
    {{- .Values.nginx.html | nindent 4 }}